name: cakephp-git-clone

on: pull_request

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CakePHP Project Git Clone
        run: git clone https://github.com/cakephp/app.git backend
      - name: Docker Compose Version
        run: docker-compose --version
      - name: Build Docker
        run: |
          cd infrastructure
          docker-compose build
          docker-compose up -d
      - name: Composer Install
        run: |
          cd infrastructure
          docker-compose exec -T app composer install
          docker-compose exec -T app cp config/app_local.example.php config/app_local.php
          docker-compose exec -T app sed -i '0,/localhost/ s/localhost/db/' config/app_local.php
      - name: PHP and CakePHP Version
        run: |
          cd infrastructure
          docker-compose exec -T app php --version
          docker-compose exec -T app cat vendor/cakephp/cakephp/VERSION.txt
      - name: CakePHP Migrate
        run: |
          cd infrastructure
          docker-compose exec -T app bin/cake migrations migrate
      - name: CakePHP Testing
        run: |
          cd infrastructure
          docker-compose exec -T app composer test
